apiVersion: v1
kind: Pod
metadata:
  name: terminal
  namespace: dev
  labels:
    app: terminal
spec:
  containers:
    - name: terminal
      image: ubuntu
      command: ["sleep", "9999999"]
      
