apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: foo
  name: service-reader
rules:
  - apiGroups: [""]
    verbs: ["get", "list"]
    resources: ["services"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pv-reader
rules:
  - apiGroups: [""]
    verbs: ["get", "list"]
    resources: [services, persistentvolumes]  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: foo
  name: pv-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pv-reader
subjects:
  - kind: ServiceAccount
    namespace: foo
    name: default
---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: RoleBinding
#metadata:
#  namespace: foo
#  name: test
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: Role
#  name: service-reader
#subjects:
#  - kind: ServiceAccount
#    name: default
#    namespace: foo
#  - kind: ServiceAccount
#    name: default
#    namespace: bar
---
apiVersion: v1
kind: Namespace
metadata:
  name: foo
---
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: foo
  labels:
    app: rbac
spec:
  serviceAccountName: default
  containers:
    - name: main
      image: luksa/kubectl-proxy
---
apiVersion: v1
kind: Namespace
metadata:
  name: bar
---
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: bar
  labels:
    app: rbac
spec:
  containers:
    - name: main
      image: luksa/kubectl-proxy