apiVersion: v1
kind: Service
metadata:
  name: ext-svc
  namespace: dev
spec:
  type: ExternalName
  externalName: www.google.com
  ports:
  - port: 80
#apiVersion: v1
#kind: Endpoints
#metadata:
#  namespace: ext-svc
#subsets:
#  - addresses:
#    - ip: 125.209.222.142
#    ports:
#    - port: 80