---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fortune-ingree
  namespace: dev
  labels:
    app: fortune
spec:
  rules:
    - host: siwoo.fortune.com
      http:
        paths:
          - backend:
              servicePort: 80
              serviceName: fortune
---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: fortune
  labels:
    app: fortune
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30123
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: fortune
  namespace: dev
  labels:
    app: fortune
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - fortune
  template:
    metadata:
      namespace: dev
      labels:
        app: fortune
    spec:
      containers:
        - name: html-generator
          image: sm123tt/fortune
          volumeMounts:
          - name: html
            mountPath: /var/htdocs
        - name: web-server
          image: nginx:alpine
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
              readOnly: true
          ports:
            - containerPort: 80
              protocol: TCP
      volumes:
      - name: html
        emptyDir:
          medium: Memory
