apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: dev
  name: kubia
  labels:
    app: kubia
spec:
  rules:
    - host: www.kubia.com
      http:
        paths:
          - backend:
              servicePort: 80
              serviceName: kubia
---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: kubia
  labels:
    app: kubia
spec:
  type: NodePort
  selector:
    app: kubia
  sessionAffinity: ClientIP
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30124
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: kubia
  labels:
    app: kubia
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - kubia
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
        - name: main
          image: sm123tt/kubia:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 8080